add: HTML Lists
bellshade/HTML-CSS pull request #17
Opened 2021-10-02 12:45 UTC by dhafitf

2021-10-02 16:32 UTC, slowy07 requested changes
terima kasih telah bekontribusi tetapi sepertinya pada file ``HTML LIsts.md`` memiliki perbedaan dengan yang lainnya, bisakah kamu merubah nama filenya ?, kemudian kami akan mengeceknya kembali, terima kasih!

2021-10-02 17:07 UTC, dhafitf commented
Sudah saya rename file `HTML LIsts.md` ke `HTML Lists.md`

2021-10-03 03:02 UTC, slowy07 approved these changes

2021-10-03 03:02 UTC, slowy07 commented
request @bellshade/htmlcss-team

2021-10-03 03:07 UTC, merged

2021-10-03 03:07 UTC, kingramzy commented
mantul