responsive navbar tempalte
bellshade/HTML-CSS pull request #200
Opened 2021-10-27 04:16 UTC by hasheemi

# Deskripsi (Description)

# Checklist:
##### Umum:
- [ ] Saya menambah kode basic terbaru.
- [ ] Saya memperbaiki kode basic yang sudah ada.
- [x] Saya menambah template terbaru.
- [ ] Saya memperbaiki template yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [ ] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/HTML-CSS/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [x] Saya telah menambahkan komentar kode yang memberikan penjelasan maksud dari kode yang saya buat.
 - [x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

# Environment
Saya menggunakan (I'm using):

- ``os`` = ``linux / windows / macOS``

## Testing

- [x] link html
- [x] lint css

linked issue #NOMOR_ISSUE

2021-10-30 13:35 UTC, hendraaagil approved these changes

2021-10-30 16:45 UTC, LevianthProject commented
### **Saran Perbaikan :**
Klik button open di mobile ada bug seperti tidak seharusnya seperti itu, silahkan di check dan disarankan menggunakan cara lain untuk membuka itu!
Silahkan atur font size untuk bagian mobilenya! 
Usahakan menggunakan tag img di bagian logo agar lebih mudah untuk diubah-ubah oleh pengguna lain tanpa harus membuat tag imgnya dari awal!

### **Saran Tambahan :**
List menu disarankan menggunakan :active state untuk setiap kliknya agar lebih bagus!
Silahkan buat beberapa versi dan warna karena template navbar ini sudah cukup bagus dan mungkin bisa jadi makin bagus lagi dengan cara menambahkan beberapa versi yang berbeda!

2021-10-31 08:43 UTC, Vins2106 approved these changes
LGTM 🔥

2021-11-05 03:12 UTC, dhafitf requested changes
Mohon konflik-nya diperbaiki terlebih dahulu dengan cara menghapus file `DIRECTORY.md`

2021-11-07 10:34 UTC, faridnizam commented
Maaf om. Saya close karena sudah melewati waktu yang ditentukan. Leader saya sudah mengingatkan tapi om belum meng koreksi nya. Jadi kalau mau mengkoreksi, mohon membuat PR yang baru.
Terima Kasih ❤️

2021-11-07 10:34 UTC, closed without merging