Pejuang push rank
bellshade/HTML-CSS pull request #211
Opened 2021-11-03 15:01 UTC by kingramzy

# Deskripsi (Description)

# Checklist:
##### Umum:
- [v] Saya menambah kode basic terbaru.
- [v] Saya memperbaiki kode basic yang sudah ada.
- [ ] Saya menambah template terbaru.
- [ ] Saya memperbaiki template yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [ ] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [v] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/HTML-CSS/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [v] Saya telah menambahkan komentar kode yang memberikan penjelasan maksud dari kode yang saya buat.
 - [v] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

# Environment
Saya menggunakan (I'm using):

- ``os`` = ``linux / windows / macOS``

## Testing

- [v] link html
- [ ] lint css

linked issue #NOMOR_ISSUE

2021-11-03 15:04 UTC, slowy07 commented
resolve confict, samain yang templatenya ke head main kak

2021-11-03 15:39 UTC, kingramzy commented
> 
> 
> resolve confict, samain yang templatenya ke head main kak

> sudah sensei

2021-11-03 15:44 UTC, slowy07 approved these changes
LGTM

2021-11-03 23:40 UTC, DevinWinando requested changes

2021-11-03 23:40 UTC, DevinWinando commented on HTML/042 HTML Textarea/README.md
> +Elemen <textarea> juga menerima beberapa atribut yang umum untuk membentuk <input>, seperti pelengkapan otomatis, fokus otomatis, dinonaktifkan, placeholder, hanya baca, dan diperlukan.
punten om, yang ini saran saya jangan ditranslate attributenya, terus dikasih markdown aja attributenya

2021-11-04 10:16 UTC, kingramzy commented on HTML/042 HTML Textarea/README.md
> +Elemen <textarea> juga menerima beberapa atribut yang umum untuk membentuk <input>, seperti pelengkapan otomatis, fokus otomatis, dinonaktifkan, placeholder, hanya baca, dan diperlukan.
ok siap

2021-11-07 03:26 UTC, closed without merging

2021-11-07 03:26 UTC, kingramzy commented
ada PR lain wkwkwk