Menambahkan HTML Textarea dan HTML Link
bellshade/HTML-CSS pull request #217
Opened 2021-11-06 03:58 UTC by kingramzy

# Deskripsi (Description)

# Checklist:
##### Umum:
- [x] Saya menambah kode basic terbaru.
- [x] Saya memperbaiki kode basic yang sudah ada.
- [ ] Saya menambah template terbaru.
- [ ] Saya memperbaiki template yang sudah ada.
- [x] Saya memperbaiki dokumentasi.
- [x] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/HTML-CSS/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [x] Saya telah menambahkan komentar kode yang memberikan penjelasan maksud dari kode yang saya buat.
 - [x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

# Environment
Saya menggunakan (I'm using):

- ``os`` = ``linux / windows / macOS``

## Testing

- [x] link html
- [ ] lint css

linked issue #NOMOR_ISSUE

2021-11-06 11:59 UTC, dhafitf requested changes
Dobel PR. Mohon untuk memilih salah satu PR dari #211 atau #217.

2021-11-07 03:52 UTC, dhafitf requested changes
Mohon diperbaiki penulisannya. Serta file video pada `HTML/assets/images/Cool.mp4` itu untuk apa ya?

2021-11-07 03:52 UTC, dhafitf commented on HTML/042 HTML Textarea/README.md
> +Elemen HTML <textarea> mewakili kontrol pengeditan teks biasa multi-baris, berguna saat Anda ingin mengizinkan pengguna memasukkan teks bentuk bebas dalam jumlah yang cukup besar, misalnya komentar p
Jika ada tag HTML dalam file markdown seperti ini, sebaiknya gunakan backtick.
```suggestion
Elemen HTML `<textarea>` mewakili kontrol pengeditan teks biasa multi-baris, berguna saat Anda ingin mengizinkan pengguna memasukkan teks bentuk bebas dalam jumlah yang cukup besar, misalnya komentar pada ulasan atau formulir umpan balik.
```

2021-11-08 03:39 UTC, dhafitf requested changes
Materi pada file `HTML/027 HTML Link/README.md` bukanlah materi HTML tetapi materi HTTP.
Mohon diperbaiki.

2021-11-15 12:50 UTC, dhafitf approved these changes
Sepertinya sudah aman. LGTM 🚀

2021-11-16 15:33 UTC, closed without merging

2021-11-16 15:33 UTC, kingramzy commented
PR ulang