Pejuang push rank
bellshade/HTML-CSS pull request #223
Opened 2021-11-22 06:05 UTC by kingramzy

# Deskripsi (Description)

# Checklist:
##### Umum:
- [x] Saya menambah kode basic terbaru.
- [x] Saya memperbaiki kode basic yang sudah ada.
- [ ] Saya menambah template terbaru.
- [x] Saya memperbaiki template yang sudah ada.
- [x] Saya memperbaiki dokumentasi.
- [x] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/HTML-CSS/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [x] Saya telah menambahkan komentar kode yang memberikan penjelasan maksud dari kode yang saya buat.
 - [x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

# Environment
Saya menggunakan (I'm using):

- ``os`` = ``linux / windows / macOS``

## Testing

- [x] link html
- [ ] lint css

linked issue #NOMOR_ISSUE

2021-11-23 04:09 UTC, nomadkode commented
Di close aja nih? @kingramzy

2021-11-23 07:09 UTC, kingramzy commented
ada yang salah kah? @nomadkode

2021-11-23 16:03 UTC, dhafitf commented
Itu ntar file templatenya kehapus dong

2021-11-24 08:11 UTC, DevinWinando requested changes
Punten om, buat materi linknya kayanya salah deh om. Harusnya materi tentang tag `<link>`, bukan tag `<a>`.  

Referensi materinya bisa diambil dari sini om [W3School](https://www.w3schools.com/tags/tag_link.asp), [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link)

2021-11-28 04:15 UTC, closed without merging

2021-11-28 04:15 UTC, kingramzy commented
Salah lagi