add: menambahkan materi CSS baru 008 CSS Borders
bellshade/HTML-CSS pull request #225
Opened 2021-11-27 04:27 UTC by MZYXn

# Deskripsi (Description)

Menambahkan materi CSS baru yaitu `008 CSS Borders`

Sumber referensi:
[W3Schools](https://www.w3schools.com/css/css_border.asp)
[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/border)
[CSS-Tricks](https://css-tricks.com/almanac/properties/b/border/)

# Checklist:
##### Umum:
- [ ] Saya menambah kode basic terbaru.
- [ ] Saya memperbaiki kode basic yang sudah ada.
- [ ] Saya menambah template terbaru.
- [ ] Saya memperbaiki template yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [ ] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [ ] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/HTML-CSS/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [ ] Saya telah menambahkan komentar kode yang memberikan penjelasan maksud dari kode yang saya buat.
 - [ ] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

# Environment
Saya menggunakan (I'm using):

- ``os`` = ``linux / windows / macOS``

## Testing

- [ ] link html
- [ ] lint css

linked issue #NOMOR_ISSUE

2021-11-28 01:39 UTC, DevinWinando requested changes
Saran saya tambahin tentang border sides, misalnya `border-top`, `border-bottom`, dsb. Bisa ditambahin di setelah materi ini `Cara penggunaan style border`. Selain itu udah bagus menurut saya. Terimakasih ya udah PR di repo HTML-CSS

2021-11-28 09:42 UTC, DevinWinando approved these changes
Udah oke sih kalo dari saya. Tinggal tunggu tim docs sama tim HTML-CSS yang lain ya mas

2021-11-28 10:02 UTC, faridnizam approved these changes
Ntapss dah oke

2021-11-28 10:08 UTC, rolandopranata requested changes
Sidikit saran untuk : 

- `Property`, mungkin bisa diubah menjadi `Properti` biar lebih menegaskan itu bahasa indonesia


Untuk dibagian border style saran saya bisa digunakan kata `untuk` biar lebih jelas kegunaannya, contoh :
- `none` – untuk menghilangkan border agar tidak terlihat
- `solid` – untuk membuat border solid (bergaris tebal)
- `hidden` – untuk membuat border tersembunyi
- `dashed` – untuk membuat border berbentuk garis-garis
- `dotted` – untuk membuat border berbentuk titik-titik
- `double` – untuk membuat border memiliki dua borer (double)
- `groove` – untuk membuat border grooved 3D. Efek ini terjadi ketika ada properti `border-color`.
- ridge – untuk membuat border 3D ridge. Efek ini terjadi ketika ada properti `border-color`.
- `inset` – untuk membuat 3D border seolah-olah masuk kedalam
- `outset` – untuk membuat 3D border

Terakhir dibagian : 

- Berikut ini adalah cara penggunaan style border yang efektif : 
- Untuk cara penggunaan masih sama seperti sebelumnya yaitu :

bisa ditambahin titik dua

Trimakasih.

2021-11-28 10:13 UTC, kingramzy approved these changes
oke mantab

2021-11-29 05:38 UTC, rolandopranata approved these changes

2021-11-29 12:29 UTC, dhafitf approved these changes

2021-12-13 06:09 UTC, merged