add : Menambahkan HTML Link dan HTML TextArea
bellshade/HTML-CSS pull request #226
Opened 2021-11-30 05:37 UTC by kingramzy

# Deskripsi (Description)

# Checklist:
##### Umum:
- [x] Saya menambah kode basic terbaru.
- [x] Saya memperbaiki kode basic yang sudah ada.
- [ ] Saya menambah template terbaru.
- [ ] Saya memperbaiki template yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [ ] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/HTML-CSS/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [x] Saya telah menambahkan komentar kode yang memberikan penjelasan maksud dari kode yang saya buat.
 - [x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

# Environment
Saya menggunakan (I'm using):

- ``os`` = ``linux / windows / macOS``

## Testing

- [x] link html
- [ ] lint css

linked issue #NOMOR_ISSUE

2021-12-03 15:18 UTC, dhafitf requested changes

2021-12-03 15:18 UTC, dhafitf commented on HTML/026 HTML Link/README.md
> +- Elemen <link> adalah elemen kosong, hanya berisi atribut.
```suggestion
- Tag `<link>` mendefinisikan hubungan antara dokumen saat ini dan sumber daya eksternal.
- Tag `<link>` paling sering digunakan untuk menautkan ke external style sheet atau untuk menambahkan favicon ke situs web Anda.
- Elemen `<link>` adalah elemen kosong, hanya berisi atribut.
```

2021-12-03 15:18 UTC, dhafitf commented on HTML/026 HTML Link/README.md
> +Tag <link> juga masuk dalam kategori tabel Atribut Event HTML
```suggestion
Tag `<link>` juga masuk dalam kategori tabel Atribut Global HTML

### Atribut Event HTML

Tag `<link>` juga masuk dalam kategori tabel Atribut Event HTML
```

2021-12-20 13:57 UTC, dhafitf approved these changes

2022-02-14 04:19 UTC, nomadkode approved these changes

2022-03-07 06:35 UTC, merged