add : Menambahkan HTML Emojis dan HTML Multimedia
bellshade/HTML-CSS pull request #227
Opened 2021-11-30 06:33 UTC by kingramzy

# Deskripsi (Description)

# Checklist:
##### Umum:
- [x] Saya menambah kode basic terbaru.
- [ ] Saya memperbaiki kode basic yang sudah ada.
- [ ] Saya menambah template terbaru.
- [ ] Saya memperbaiki template yang sudah ada.
- [x] Saya memperbaiki dokumentasi.
- [x] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/HTML-CSS/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [x] Saya telah menambahkan komentar kode yang memberikan penjelasan maksud dari kode yang saya buat.
 - [x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

# Environment
Saya menggunakan (I'm using):

- ``os`` = ``linux / windows / macOS``

## Testing

- [x] link html
- [ ] lint css

linked issue #NOMOR_ISSUE

2021-12-03 15:32 UTC, dhafitf requested changes
Mohon diperbaiki. Dan juga mohon berikan contoh kode menggunakan bahasa Indonesia

2021-12-03 15:32 UTC, dhafitf commented on HTML/034 HTML Emojis/README.md
> +Sejak Emoji adalah karakter, Emoji bisa disalin, ditampilkan, dan diukur seperti karakter lain di HTML.
```suggestion
Karena Emoji adalah karakter, Emoji bisa disalin, ditampilkan, dan diukur seperti karakter lain di HTML.
```

2021-12-03 15:32 UTC, dhafitf commented on HTML/045 HTML Multimedia/README.md
> +Multimedia datang dari banyak format yang berbeda. Bisa dalam apapun yang anda dengar dan lihat, seperti gambar, musik, suara,video, rekaman, film, animasi, dan banyak lagi.
```suggestion
Multimedia datang dari banyak format yang berbeda. Bisa dalam apapun yang anda dengar dan lihat, seperti gambar, musik, suara, video, rekaman, film, animasi, dan banyak lagi.
```

2021-12-03 15:32 UTC, dhafitf commented on HTML/045 HTML Multimedia/README.md
> +Lalu datang Browser dangan dukungan untuk warna, font tulisan, gambar, dan multimedia!
```suggestion
Lalu datang Browser yang mendukung untuk warna, font tulisan, gambar, dan multimedia!
```

2021-12-03 15:32 UTC, dhafitf commented on HTML/045 HTML Multimedia/README.md
> +Elemen Multimedia(seperti audio atau video) disimpan dalam file media.
```suggestion
Elemen Multimedia (seperti audio atau video) disimpan dalam file media.
```

2021-12-03 15:32 UTC, dhafitf commented on HTML/045 HTML Multimedia/README.md
> +File multimedia punya format dan ekstensiyang berbeda beda. seperti: .wav, .mp3, .mp4, .mpg, .wmv, dan .avi .
```suggestion
File multimedia punya format dan ekstensi yang berbeda-beda. Seperti: `.wav`, `.mp3`, `.mp4`, `.mpg`, `.wmv`, dan `.avi`.
```

2021-12-03 15:32 UTC, dhafitf commented on HTML/045 HTML Multimedia/README.md
> +|  09   | MPEG-4 atau MP4 |    .mp4    |   MP4. Di develop oleh grup Moving Pictures Expert. Biasa dipakai untuk kamera video dan hardware TV. didukung oleh semua Browser dan di rekomendasikan oleh Y
```suggestion
|  01   |      MPEG       | .mpg .mpeg |                      MPEG dikembangkan oleh grup Moving Pictures Expert. Format video populer paling pertama. Tidak di dukung sama sekali oleh HTML                       |
|  02   |       AVI       |    .avi    | AVI (Audio Video Interleave). Dikembangkan oleh Microsoft. Biasa dipakai untuk kamera video dan hardware TV. Berjalan baik di Komputer Windows, tapi tidak di Web Browser |
|  03   |       WMV       |    .wmv    |  WMV (Windows Media Video). Dikembangkan oleh Microsoft. Biasa dipakai untuk kamera video dan hardware TV. Berjalan baik di Komputer Windows, tapi tidak di Web Browser   |
|  04   |    QuickTime    |    .mov    |             QuickTime. Dikembangkan oleh Apple. Biasa dipakai untuk kamera video dan hardware TV. Berjalan baik di Komputer Apple, tapi tidak di Web Browser              |
|  05   |    RealVideo    |  .rm .ram  |                 RealVideo. Dikembangkan oleh Real Media untuk membolehkan video streaming dengan bandwidth rendah. tidak bisa dijalankan di Web Browser.                  |
|  06   |      Flash      | .swf .flv  |                               Flash. Dikembangkan oleh Macromedia. Sering meminta komponen extra (plug-in) untuk dijalankan di Web Browser                                |
|  07   |       Ogg       |    .ogg    |                                                    Theora Ogg. Dikembangkan oleh fondasi Xiph.Org. di dukung oleh HTML                                                    |
|  08   |      WebM       |   .webm    |                                               WebM. Dikembangkan oleh Mozilla, Opera, Adobe, dan Google. Didukung oleh HTML                                               |
|  09   | MPEG-4 atau MP4 |    .mp4    |   MP4. Dikembangkan oleh grup Moving Pictures Expert. Biasa dipakai untuk kamera video dan hardware TV. didukung oleh semua Browser dan di rekomendasikan oleh Youtube.   |
```

2021-12-03 15:32 UTC, dhafitf commented on HTML/045 HTML Multimedia/README.md
> +|  08   |    MP4    |    .mp4    |                                                                                                                      MP4 adalah format video, tetapi juga dapat digu
```suggestion
|  01   |   MIDI    | .mid .midi | MIDI (Musical Instrument Digital Interface).. Format utama untuk semua perangkat musik elektronik seperti synthesizer dan kartu suara PC. File MIDI tidak berisi suara, tetapi catatan digital yang dapat dimainkan oleh elektronik. Berjalan dengan baik di semua komputer dan perangkat keras musik, tetapi tidak di web browser. |
|  02   | RealAudio |  .rm .ram  |                                                                                                  RealAudio. Dikembangkan oleh Real Media untuk membolehkan video streaming dengan bandwidth rendah. tidak bisa dijalankan di Web Browser.                                                                                                  |
|  03   |    WMA    |    .wma    |                                                                                                            WMA (Windows Media Audio). Dikembangkan oleh Microsoft. Berjalan baik di Komputer Windows, tapi tidak di Web Browser                                                                                                            |
|  04   |    AAC    |    .aac    |                                                                                  AAC(Advance Audio Coding). Dikembangkan oleh Apple yang dimana menjadi format bawaan iTunes. Berjalan baik di komputer Apple, tapi tidak bisa dijalankan di web browser.                                                                                  |
|  05   |    WAV    |    .wav    |                                                                                                        WAV. Dikembangkan oleh IBM dan Microsoft. Berjalan baik di Windows, Macintosh, and Sistem Operasi Linux. Di dukung oleh HTML                                                                                                        |
|  06   |    Ogg    |    .ogg    |                                                                                                                                        Ogg. Dikembangkan oleh fondasi Xiph.Org. di dukung oleh HTML                                                                                                                                        |
|  07   |    MP3    |    .mp3    |                                                            File MP3 sebenarnya adalah bagian suara dari file MPEG. MP3 adalah format paling populer untuk pengguna musik. Menggabungkan kompresi yang baik (file kecil) dengan kualitas tinggi. Didukung oleh semua browser.                                                             |
|  08   |    MP4    |    .mp4    |                                                                                                                      MP4 adalah format video, tetapi juga dapat digunakan untuk audio. Didukung oleh semua browser.                                                                                                                      |
```

2022-03-07 06:34 UTC, nomadkode commented
gimana nih? @dhafitf @kingramzy

2022-03-09 13:00 UTC, dhafitf commented
> gimana nih? @dhafitf @kingramzy

Masih banyak hal yang perlu dirubah, termasuk yang sudah saya contohkan di atas.

2022-03-09 13:06 UTC, dhafitf requested changes

2022-03-12 06:28 UTC, nomadkode commented
close aja yah, udah kelamaan

2022-03-12 06:28 UTC, closed without merging