add: Menambahkan HTML Simbol dan HTML Select
bellshade/HTML-CSS pull request #228
Opened 2021-12-01 16:00 UTC by kingramzy

# Deskripsi (Description)

# Checklist:
##### Umum:
- [x] Saya menambah kode basic terbaru.
- [ ] Saya memperbaiki kode basic yang sudah ada.
- [ ] Saya menambah template terbaru.
- [ ] Saya memperbaiki template yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [ ] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/HTML-CSS/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [x] Saya telah menambahkan komentar kode yang memberikan penjelasan maksud dari kode yang saya buat.
 - [x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

# Environment
Saya menggunakan (I'm using):

- ``os`` = ``linux / windows / macOS``

## Testing

- [x] link html
- [ ] lint css

linked issue #NOMOR_ISSUE

2021-12-03 15:37 UTC, dhafitf requested changes
Mohon gunakan bahasa Indonesia

2021-12-03 15:37 UTC, dhafitf commented on HTML/038 HTML Select/README.md
> +Tag <link> juga masuk dalam kategori tabel Atribut Event HTML
Ini kenapa ada tag `<link>` ya?

2021-12-03 15:37 UTC, dhafitf commented on HTML/038 HTML Select/README.md
> +tidak ada.
```suggestion
```

2021-12-04 01:24 UTC, kingramzy commented on HTML/038 HTML Select/README.md
> +Tag <link> juga masuk dalam kategori tabel Atribut Event HTML
bukannya memang tag link bukan tag a?

2022-01-20 13:06 UTC, EmptyWork requested changes

2022-01-20 13:06 UTC, EmptyWork commented on HTML/033 HTML Symbols/README.md
> +I will display € I will display € I will display €
karena `<p>` memiliki default `display: block`, maka output menjadi beberapa baris
```suggestion
I will display € 
I will display € 
I will display €
```

2022-01-20 13:06 UTC, EmptyWork commented on HTML/033 HTML Symbols/README.md
> +|  10   |  ∑   | &#8721; |  &sum;   |   N-ARY SUMMATION    |
Mungkin deskripsinya lebih bagus diubah menjadi Bahasa Indonesia untuk bagian ini

2022-03-07 06:34 UTC, nomadkode commented
gimana nih

2022-03-12 06:28 UTC, nomadkode commented
close juga ini

2022-03-12 06:28 UTC, closed without merging