Memberikan `font-family` pada `@font-face`
bellshade/HTML-CSS pull request #235
Opened 2022-03-24 12:43 UTC by syahid246

# Deskripsi (Description)
Memberikan `font-family` pada `@font-face`, dan cara menggunakannya. Supaya dapat mengetahui bagaimana cara menggunakan dan mencobanya. Sehingga dapat menghindari pembaca bingung
"loh, gimana cara gunainnya ini? Nama font di CSS-nya apa?"

Serta memberikan sumber tambahan dari [stackoverflow](https://stackoverflow.com/questions/12812441/how-do-i-use-woff-fonts-for-my-website).

# Checklist:
##### Umum:
- [x] Saya menambah kode basic terbaru.
- [ ] Saya memperbaiki kode basic yang sudah ada.
- [ ] Saya menambah template terbaru.
- [ ] Saya memperbaiki template yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [ ] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/HTML-CSS/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [x] Saya telah menambahkan komentar kode yang memberikan penjelasan maksud dari kode yang saya buat.
 - [x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

# Environment
Saya menggunakan (I'm using):

- ``os`` = ``windows``

## Testing

- [ ] link html
- [ ] lint css

linked issue #234

2022-03-31 06:16 UTC, dhafitf requested changes

2022-03-31 06:16 UTC, dhafitf commented on CSS/019 CSS Web Font/README.md
> +  font-family: "Font Pertamaku";
Ini contohnya dijadikan satu saja. Pindahkan `body` ke bawah `@font-face`.

2022-03-31 06:20 UTC, dhafitf requested changes

2022-03-31 06:20 UTC, dhafitf commented on CSS/019 CSS Web Font/README.md
> +  font-family: "Font Pertamaku";
```suggestion
  font-family: "Font Pertamaku";
}

body {
  font-family: "Font Pertamaku";
}
```

2022-03-31 06:20 UTC, dhafitf commented on CSS/019 CSS Web Font/README.md
> +  font-family: "Font Pertamaku";
Ini contohnya dijadikan satu saja. Pindahkan `body` ke bawah `@font-face`.

2022-04-01 09:54 UTC, syahid246 commented on CSS/019 CSS Web Font/README.md
> +  font-family: "Font Pertamaku";
saya edit, atau saya click resolve conversation ya?

2022-04-02 15:03 UTC, dhafitf commented on CSS/019 CSS Web Font/README.md
> +  font-family: "Font Pertamaku";
Harusnya di edit terlebih dahulu, baru klik resolve conversation. Tapi gpp, sekarang edit, kemudian lakukan commit lagi.

2022-04-03 04:25 UTC, syahid246 commented on CSS/019 CSS Web Font/README.md
> +}
Ini sebaiknya di hilangkan saja kak @dhafitf

2022-04-17 06:20 UTC, dhafitf approved these changes

2022-04-17 06:20 UTC, merged