docs: menambah dokumentasi baru soal CSS Icon
bellshade/HTML-CSS pull request #255
Opened 2022-10-03 18:08 UTC by pamela-sarnia

# Deskripsi (Description)

# Checklist:
##### Umum:
- [ ] Saya menambah kode basic terbaru.
- [ ] Saya memperbaiki kode basic yang sudah ada.
- [ ] Saya menambah template terbaru.
- [ ] Saya memperbaiki template yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [x Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/HTML-CSS/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [x] Saya telah menambahkan komentar kode yang memberikan penjelasan maksud dari kode yang saya buat.
 - [x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

# Environment
Saya menggunakan (I'm using):

- ``os`` = ``windows``

## Testing

- [x] link html
- [ ] lint css

linked issue #NOMOR_ISSUE

2022-10-03 22:41 UTC, slowy07 requested changes
LGTM, tetapi salah dalam penempatan file ``README.md`` nya, jika di merge akan mengganti bagian [``README`` ini](https://github.com/bellshade/HTML-CSS/blob/main/README.md), file ini seharusnya dimasukkan dalam direktori [``CSS``](https://github.com/bellshade/HTML-CSS/tree/main/CSS)

untuk penambahannya silahkan dibuat pada direktori ``CSS`` dengan cara:

- masuk ke direktori ``CSS``
- kemudian buat folder yang bernama ``058 CSS google font``
- di dalam folder tersebut isi ``README.md`` yang berisi materi penjelasan tentang ``CSS google font``

2022-10-04 01:08 UTC, pamela-sarnia commented
> LGTM, tetapi salah dalam penempatan file `README.md` nya, jika di merge akan mengganti bagian [`README` ini](https://github.com/bellshade/HTML-CSS/blob/main/README.md), file ini seharusnya dimasukkan dalam direktori [`CSS`](https://github.com/bellshade/HTML-CSS/tree/main/CSS)
> 
> untuk penambahannya silahkan dibuat pada direktori `CSS` dengan cara:
> 
> * masuk ke direktori `CSS`
> * kemudian buat folder yang bernama `058 CSS google font`
> * di dalam folder tersebut isi `README.md` yang berisi materi penjelasan tentang `CSS google font`

oke sensei

2022-10-04 04:22 UTC, dhafitf commented
> LGTM, tetapi salah dalam penempatan file `README.md` nya, jika di merge akan mengganti bagian [`README` ini](https://github.com/bellshade/HTML-CSS/blob/main/README.md), file ini seharusnya dimasukkan dalam direktori [`CSS`](https://github.com/bellshade/HTML-CSS/tree/main/CSS)
> 
> untuk penambahannya silahkan dibuat pada direktori `CSS` dengan cara:
> 
> * masuk ke direktori `CSS`
> * kemudian buat folder yang bernama `058 CSS google font`
> * di dalam folder tersebut isi `README.md` yang berisi materi penjelasan tentang `CSS google font`

Benar sekali, file `README.md` harus berada dalam folder CSS dan `021 CSS Icons`, seperti yang sudah tercantum pada #204

2022-10-04 04:39 UTC, pamela-sarnia commented
> > LGTM, tetapi salah dalam penempatan file `README.md` nya, jika di merge akan mengganti bagian [`README` ini](https://github.com/bellshade/HTML-CSS/blob/main/README.md), file ini seharusnya dimasukkan dalam direktori [`CSS`](https://github.com/bellshade/HTML-CSS/tree/main/CSS)
> > untuk penambahannya silahkan dibuat pada direktori `CSS` dengan cara:
> > 
> > * masuk ke direktori `CSS`
> > * kemudian buat folder yang bernama `058 CSS google font`
> > * di dalam folder tersebut isi `README.md` yang berisi materi penjelasan tentang `CSS google font`
> 
> Benar sekali, file `README.md` harus berada dalam folder CSS dan `021 CSS Icons`, seperti yang sudah tercantum pada #204

sudah pull request yang baru

2022-10-04 04:45 UTC, dhafitf commented
> > > LGTM, tetapi salah dalam penempatan file `README.md` nya, jika di merge akan mengganti bagian [`README` ini](https://github.com/bellshade/HTML-CSS/blob/main/README.md), file ini seharusnya dimasukkan dalam direktori [`CSS`](https://github.com/bellshade/HTML-CSS/tree/main/CSS)
> > > untuk penambahannya silahkan dibuat pada direktori `CSS` dengan cara:
> > > 
> > > * masuk ke direktori `CSS`
> > > * kemudian buat folder yang bernama `058 CSS google font`
> > > * di dalam folder tersebut isi `README.md` yang berisi materi penjelasan tentang `CSS google font`
> > 
> > 
> > Benar sekali, file `README.md` harus berada dalam folder CSS dan `021 CSS Icons`, seperti yang sudah tercantum pada #204
> 
> sudah pull request yang baru

Baik, kalau begitu PR ini saya tutup.

2022-10-04 04:45 UTC, closed without merging