docs: menambahkan materi css google fonts
bellshade/HTML-CSS pull request #260
Opened 2022-10-04 14:33 UTC by pamela-sarnia

# Deskripsi (Description)

# Checklist:
##### Umum:
- [ ] Saya menambah kode basic terbaru.
- [ ] Saya memperbaiki kode basic yang sudah ada.
- [ ] Saya menambah template terbaru.
- [ ] Saya memperbaiki template yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [x] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/HTML-CSS/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [x] Saya telah menambahkan komentar kode yang memberikan penjelasan maksud dari kode yang saya buat.
 - [x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

# Environment
Saya menggunakan (I'm using):

- ``os`` = ``windows``

## Testing

- [x] link html
- [ ] lint css

linked issue #NOMOR_ISSUE

2022-10-04 15:10 UTC, dhafitf commented on CSS/020 CSS Google Fonts/README.MD
> +![Contoh Penggunakan Google Fonts](https://i.ibb.co/fMrksbG/Screenshot-2022-10-03-230101.png)
```suggestion
1. Copy link style sheet dari Google Fonts dan paste link tersebut di bagian <head> pada file HTML.

![Link Style Sheet Google Fonts](https://i.ibb.co/CHt7DKk/Screenshot-2022-10-03-224721.png)

2. Cantumkan nama font tersebut pada CSS.

### Contoh

Misalnya, kita ingin menggunakan font "Silkscreen" dari Google Fonts:

```HTML 
<head>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Silkscreen&display=swap" rel="stylesheet">
  <style>
    body {
      font-family: "Silkscreen", cursive;
    }
  </style>
</head>
```

Hasil:
![Contoh Penggunakan Google Fonts](https://i.ibb.co/fMrksbG/Screenshot-2022-10-03-230101.png)
```
Kode tersebut tidak menunjukkan bahwa "Ada dua cara untuk menggunakan Google Fonts". Kode tersebut hanya menunjukkan cara cepat mengubah font family dari google jika pembuat kode sudah paham/tahu tautan dari google font. Namun secara keseluruhan, cara yang dilakukan tetaplah sama.

2022-10-05 15:21 UTC, dhafitf requested changes
Sama satu lagi, kemarin ketinggalan yang ini. Mohon diperbaiki

2022-10-05 15:21 UTC, dhafitf commented on CSS/020 CSS Google Fonts/README.MD
> +Jika kamu ingin menggunakan beberapa Google Fonts, cukup paste semua link dari Google Fonts di <head>. Atau, gunakan link style sheet dan sebutkan semua nama font dengan dipisahkan oleh tanda ( | ).
```suggestion
Jika kamu ingin menggunakan beberapa Google Fonts, cukup paste semua link dari Google Fonts pada tag `<head>`. Atau gunakan satu link style sheet dan sebutkan semua nama font dengan dipisahkan oleh tanda ( | ).
```

2022-10-06 11:18 UTC, pamela-sarnia commented
> Sama satu lagi, kemarin ketinggalan yang ini. Mohon diperbaiki

sudah diperbaiki ya

2022-10-07 15:37 UTC, merged