docs: 044 HTML SVG
bellshade/HTML-CSS pull request #270
Opened 2022-10-24 03:23 UTC by fadelun

# Deskripsi (Description)

# Checklist:
##### Umum:
- [x] Saya menambah kode basic terbaru.
- [ ] Saya memperbaiki kode basic yang sudah ada.
- [ ] Saya menambah template terbaru.
- [ ] Saya memperbaiki template yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [x] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/HTML-CSS/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [x] Saya telah menambahkan komentar kode yang memberikan penjelasan maksud dari kode yang saya buat.
 - [x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

# Environment
Saya menggunakan (I'm using):

- ``os`` = ``windows``

## Testing

- [x] link html
- [ ] lint css

linked issue #203

2022-10-24 03:56 UTC, AdityaFitrianaNS approved these changes
LGTM 🚀

2022-10-24 13:54 UTC, dhafitf requested changes

2022-10-24 13:54 UTC, dhafitf commented on HTML/044 HTML SVG/README.md
> +Tidak disarankan untuk menggunakan cara ini karena akan sulit untuk di _maintain_ dan dampak buruk bagi SEO.
```suggestion
> Tidak disarankan untuk menggunakan tag `<iframe>` karena akan sulit untuk di _maintain_ dan dampak buruk bagi SEO.
```

2022-10-24 13:54 UTC, dhafitf commented on HTML/044 HTML SVG/README.md
> +       color the line will not be visible -->
Ubah penjelasan ini menjadi bahasa Indonesia.

2022-10-25 16:52 UTC, dhafitf approved these changes
LGTM 🚀

2022-10-25 16:53 UTC, merged