add: 045 HTML Multimedia
bellshade/HTML-CSS pull request #276
Opened 2023-05-25 12:58 UTC by fadelun

# Deskripsi (Description)

# Checklist:
##### Umum:
- [ ] Saya menambah kode basic terbaru.
- [ ] Saya memperbaiki kode basic yang sudah ada.
- [ ] Saya menambah template terbaru.
- [ ] Saya memperbaiki template yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [x] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/HTML-CSS/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [ ] Saya telah menambahkan komentar kode yang memberikan penjelasan maksud dari kode yang saya buat.
 - [x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

# Environment
Saya menggunakan (I'm using):

- ``os`` = ``windows``

## Testing

- [x] link html
- [ ] lint css

linked issue #203

2023-05-28 11:07 UTC, dhafitf requested changes

2023-05-28 11:07 UTC, dhafitf commented on HTML/045 HTML Multimedia/README.md
> +### contoh penulisan pada HTML:
Gunakan hurus kapital untuk awalan sebuah judul.
```suggestion
### Contoh penulisan pada HTML:
```

2023-05-28 11:07 UTC, dhafitf commented on HTML/045 HTML Multimedia/README.md
> +**penjelasan**
Lebih baik menggunakan h4.
```suggestion
#### Penjelasan
```

2023-05-28 11:07 UTC, dhafitf commented on HTML/045 HTML Multimedia/README.md
> +- autoplay : agar video berjalan secara otomatis.
Video sudah berjalan secara otomatis jika dalam kondisi `play`. 
Gunakan penjelasan yang lebih jelas seperti saran di bawah ini.
```suggestion
- autoplay : untuk memulai video secara otomatis.
```

2023-05-28 11:07 UTC, dhafitf commented on HTML/045 HTML Multimedia/README.md
> +### contoh penulisan pada HTML:
Gunakan hurus kapital untuk awalan sebuah judul.
```suggestion
### Contoh penulisan pada HTML:
```

2023-05-28 11:07 UTC, dhafitf commented on HTML/045 HTML Multimedia/README.md
> +```
Tambahkan bahasa yang digunakan pada kode agar kode ter-highlight.
```suggestion
```html
<audio controls autoplay>
  <source src="horse.ogg" type="audio/ogg">
  <source src="horse.mp3" type="audio/mpeg">
Your browser does not support the audio element.
</audio>
```
```

2023-05-31 23:07 UTC, fadelun commented on HTML/045 HTML Multimedia/README.md
> +Multimedia itu adalah seperti yang sering kita jumpai berupa musik, suara, video, film dan animasi.
baik kak

2023-05-31 23:09 UTC, fadelun commented on HTML/045 HTML Multimedia/README.md
> +Multimedia itu adalah seperti yang sering kita jumpai berupa musik, suara, video, film dan animasi.
sepertinya bagian ini dihapus aja ya kak

2023-06-12 17:05 UTC, dhafitf approved these changes

2023-06-12 17:06 UTC, merged